project:
  type: website

website:
  open-graph: true
  search: true
  navbar:
    logo: rseed-neg.png
    logo-alt: "Research Software Engineering and Economic Data at KOF Lab"
    left:
      - href: startpage/ed/index.qmd
        text: Data
      - href: startpage/rse/index.qmd
        text: Software
      - href: startpage/teaching/index.qmd
        text: Courses
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: Team
      - href: community.qmd
        text: Community
      - href: blog.qmd
        text: blog
  page-footer: 'RSEED is a part of KOF Lab at ETH Zurich.' 



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



