project:
  type: website

website:
  title: "RSEED"
  search: true
  navbar:
    left:
      - href: data.qmd
        text: Data
      - href: software.qmd
        text: Software
      - href: courses.qmd
        text: Courses
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: Team
      - href: community.qmd
        text: Community
      - href: blog.qmd
        text: blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



