project:
  type: website

website:
  open-graph: true
  search: true
  navbar:
    logo: rseed-pos.png
    logo-alt: "Research Software Engineering and Economic Data at KOF Lab"
    left:
      - href: h4sci.qmd
        text: Hacking for Science
      - href: opnts-ord-proposal/
        text: Open Time Series
      - href: about.qmd
        text: Team
      - href: community.qmd
        text: Join us on Matrix!
      - href: blog.qmd
        text: blog
  page-footer: 'RSEED is a part of [KOF Lab at ETH Zurich](https://kof.ethz.ch/en/the-institute/kof-divisions/research-division-kof-lab/rseed.html#).'



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      text: |
        <script defer data-domain="rseed.ch" src="https://plausible.io/js/script.js"></script>
