---
title: "Hacking for Science Is Back!"
---

By popular demand, we're bringing the Hacking for Science course back to the D-MTEC PhD program in fall 2024.
The course will open to guests from all departments as well as interested guests. 
We are currently updating the course website, stay tuned and subscribe to our newsletter in the meantime. 

To learn more about the course, including an initial schedule, check our [blog post on the h4sci project](posts/h4sci/).



::: {.column-margin}

**Feedback, Questions, Ideas?**

Contact us. 

**Minna Heim**

heim [ at ] kof.ethz.ch

<br><br>


**Newsletter Registration**

Stay informed about new courses and trainings. [Join the quarterly RSEED newsletter](https://kof.ethz.ch/en/the-institute/kof-divisions/research-division-kof-lab/rseed/subscription.html).

```{r, echo=FALSE}
library(qrcode)

q <- qrcode::qr_code("https://kof.ethz.ch/en/the-institute/kof-divisions/research-division-kof-lab/rseed/subscription.html")
plot(q)

```

:::



## Hacking for Science, ETH PhD program

Hacking for Science is a highly interactive, online course providing non-computer science students valuable big picture guidance and teaching hands-on software development skills. The course aims to help researchers of all fields who embrace programming as part of their approach to working with data. 
Hacking for Science is part of D-MTEC offering for PhD students but has benefited from guests from academia as well as the public and private sector. 

[Hacking for Science ETH Course Catalog](https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?semkez=2022W&ansicht=KATALOGDATEN&lerneinheitId=161937&lang=en) | [Research Software Engineering - A Guide to the Open Source Ecosystem](https://rse-book.github.io) | [2022 KITE Award nomnination](https://ethz.ch/en/the-eth-zurich/education/innovation/kite-award/kite-award-2022/nominierte-projekte-kite-award-2022/hacking-for-social-sciences.html)


