---
title: "RSEED at KOF Lab"
description: "In 2023, the KOF Swiss Economic Institute started KOF Lab as a new research devision to develop, test and implement new approaches to economic research. *Research Software Engineering and Economic Data (RSEED)* starts as one of four KOF Lab sections alongside *Medium and Long-Term Scenarios*, *Inequality and Public Economics* and *Public and Social Policy Design*."
author: "Matthias Bannert"
date: "11/01/2023"
categories:
    - research software engineering
    - economic data
    - teaching
    - RSEED news
---


```{r, message=FALSE, warnings=FALSE}
#| code-fold: true
install.packages("cranlogs", repos = "http://cran.us.r-project.org")
library(cranlogs)
library(dplyr)
library(lubridate)
library(tsbox)
top <- cranlogs::cran_top_downloads()

packs <- cranlogs::cran_downloads(
    from = "2015-01-01",
    to = "2023-09-30"
)

packs |>
    group_by(floor_date(date, "month")) |>
    summarize(m = sum(count)) |>
    ts_plot(
        title = "Sum of Monthly R Package Downloads",
        subtitle = "source: RStudio CRAN mirror"
    )



```

The aim of the newly launched [KOF Lab](https://kof.ethz.ch/en/the-institute/kof-divisions/research-division-kof-lab.html) section is to become a competence hub for Research Software Engineering and Economic Data in Switzerland and beyond. The section aims to enable more researchers to work with KOF's unique datasets an to help use the potential of programming as a channel to communicate methodological advances and new analyses. In addition, RSEED provides courses to help non-computer science scholars bolster their computational competencies.


## What to Expect from RSEED?


RSEED's initial offering includes working with the [KOF Micro Data Center](https://kof.ethz.ch/daten/kof-micro-data-centre.html), the course [Hacking for Science](https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?semkez=2022W&ansicht=KATALOGDATEN&lerneinheitId=161937&lang=en) along with the book project [*Research Software Engineering - A Guide to the Open Source Ecosystem*](https://rse-book.github.io) as well as several software package projects. Short term future plans include the launch of a new innovative seminar. 

## What to Expect from this Blog?

Besides section news, tutorials and an occasional discussion of highlights in the field, expect the blog 
to accompany the RSEED seminar. We invite speakers to present their topic in a blog post before their actual presentation. This form of pre-circulated content is intended to help drive the discussion,  improve feedback at the live event and allow to catch-up for debriefing. In addition to the blog, the seminar has its own channel on the RSEED matrix chat space. 


